### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by Mattsav** [endail/hx711-rpi-py#8]
Hi,

I'm trying to install it on a raspi4 using pip install hx711-rpi-py.

Its says its installed but python can't find it. Any ideas?

Regards

Matt

**Comment by Mattsav** [comment]
I've also tried it with pip3 and sudo pip sudo pip3

**Comment by Mattsav** [comment]
I just tried that followed by pip intsall but it still can't find it for some reason

**Comment by Mattsav** [comment]
this works pi@raspberrypi:~/hx711 $ bin/simplehx711test 2 3 -377 -363712 so its just python that can't find it

**Comment by endail** [comment]
After you installed the C++ library, did you run `sudo ldconfig`? If not, try that.

**Comment by Mattsav** [comment]
That worked !

Thanks for the library and your help :)
