### ISSUE TITLE
Install problem using python 

### ISSUE THREAD

**Issue by Compocity** [endail/hx711-rpi-py#9]
Hello,

I'am currently using the library with python on a Raspberry pi 4 b, raspbian 11 bullseye.
Although I followed precisely the install steps, I am getting a syntax error with the following message:

Traceback (most recent call last):
  File "/home/pi/App/main.py", line 16, in <module>
    communication = Communication()
  File "/home/pi/App/Communication.py", line 85, in __init__
    self.scale1 = SimpleHX711(self.hx711_data1,self.hx711_sck1_pin, 95014, 150000)
NameError: name 'SimpleHX711' is not defined

I've tried everything I've could but did not find any solution. The cpp binaries are built and working well.

**Comment by endail** [comment]
There are two possibilities I can think of:

- Do you have `from HX711 import *` included before trying to use `SimpleHX711`?

- If yes, run `sudo ldconfig` in a terminal then give it another try. I recently removed that command from the install script, so you may need to invoke it manually.

**Comment by Compocity** [comment]
I see, there was a mistake in the code.

In the header there was  `from hx711 import *` instead of `HX711` that caused the issue.

Thank you!

**Comment by Compocity** [comment]
Closing issue
